bind:
  admin:
    mount: /admin


router:
  http.get:
    admin.core.dashboard:
      "": ~

    admin.core.global_settings.index:
      "/core/global_settings":

    admin.core.global_settings.edit:
      "/core/global_settings/{group}":
        group: /\S+/

    admin.core.rebuild:
      "/rebuild": ~

    common.robots:
      "/robots.txt": ~

    common.sitemap:
      "/sitemap.xml": ~

    common.faq_markup:
      "/faq/markup": ~

  bin:
    core.assets:
      "/assets/{path}":
        path: /.+/

    core.gridfs:
      "/files/{bucket}":
        bucket: /.+/

    core.gridfs_tmp:
      "/tfs/{bucket}":
        bucket: /.+/
